service: createslackchannel

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-northeast-1
  deploymentBucket: ${file(./myCustomFile.yml):deployment_bucket}
  logRetentionInDays: 7
  timeout: 60
  memorySize: 128
  environment:
    TZ: Asia/Tokyo
    SLACK_TOKEN: ${file(./myCustomFile.yml):slack_token}
    POST_CHANNEL: ${file(./myCustomFile.yml):post_channel}
    EXEC_USER_ID: ${file(./myCustomFile.yml):exec_user_id}

package:
  exclude:
    - dist/**
    - build.sh
    - src/example.log
    - src/example.py
    - lambda_function.zip
    - myCustomFile.yml

plugins:
  - serverless-prune-plugin
  - serverless-plugin-aws-alerts
  - serverless-python-requirements

functions:
  main:
    handler: src/main.lambda_handler
    timeout: 180
    events:
      - schedule:
#         rate: cron(5 * * * ? *) #for test
         rate: cron(0 11 1 * ? *)

custom: ${file(./myCustomFile.yml)}
